LogisticsWebsite_WebProgramingProject/Models/Schedule.cs
using System;
using System.Collections.Generic;

namespace LogisticsWebsite_WebProgramingProject.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int? ShipId { get; set; }

    public int Pol { get; set; }

    public int Pod { get; set; }

    public decimal Price { get; set; }

    public DateOnly DayGo { get; set; }

    public TimeOnly? TimeGo { get; set; }

    public DateOnly DayCome { get; set; }

    public virtual ICollection<BillOfLading> BillOfLadings { get; set; } = new List<BillOfLading>();

    public virtual Port PodNavigation { get; set; } = null!;

    public virtual Port PolNavigation { get; set; } = null!;

    public virtual Ship? Ship { get; set; }
}

LogisticsWebsite_WebProgramingProject/Controllers/BookingInfomationController.cs
using LogisticsWebsite_WebProgramingProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using LogisticsWebsite_WebProgramingProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
namespace LogisticsWebsite_WebProgramingProject.Controllers
{
    [Authorize]
    public class BookingInfomationController : Controller
    {
        private readonly IBillofladingRepository _billofladingRepository;
        private readonly IBookinginfomationRepository _bookinginfomationRepository;
        private readonly IPortRepository _portReponsitory;
        private readonly IScheduleRepository _scheduleReponsitory;
        private readonly LogisticsContext _logisticsContext;
        private readonly IContainerRepository _ContainerReponsitory;
        private readonly UserManager<ApplicationUser> _userManager;
        public BookingInfomationController(LogisticsContext logisticsContext, IBookinginfomationRepository bookinginfomationRepository, IBillofladingRepository billofladingRepository,
            IScheduleRepository scheduleReponsitory, IPortRepository portReponsitory, IContainerRepository containerReponsitory, UserManager<ApplicationUser> userManager)
        {
            _logisticsContext = logisticsContext;
            _billofladingRepository = billofladingRepository;
            _bookinginfomationRepository = bookinginfomationRepository;
            _scheduleReponsitory = scheduleReponsitory;
            _portReponsitory = portReponsitory;
            _userManager = userManager;
            _ContainerReponsitory = containerReponsitory;
        }

        public async Task<IActionResult> Index()
        {
            var schedules = await _logisticsContext.Schedules
              .Include(s => s.PodNavigation)
              .Include(s => s.PolNavigation)
              .Include(s => s.Ship)
              .ToListAsync();
            return RedirectToAction("CreateBillOfLading", "BillOfLading");
        }

        public async Task<IActionResult> Add()
        {
            // Truy xuất danh sách các cảng từ repository
            var ports = await _portReponsitory.GetAllAsync();
            var portItems = ports.Select(p => new SelectListItem
            {
                Text = p.Name,
                Value = p.Name.ToString()
            }).ToList();
            var priceOwnerOptions = new List<SelectListItem>
             {
                   new SelectListItem { Text = "Yes", Value = "true" },
                   new SelectListItem { Text = "No", Value = "false" }
             };
           
        
            //Gán danh sách các mục cảng cho ViewBag hoặc ViewModel
            ViewBag.Ports = portItems;
            ViewBag.PriceOwnerOptions = priceOwnerOptions;
            var viewModel = new BookingInfomation();
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(BookingInfomation bookinginfo)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var today = DateOnly.FromDateTime(DateTime.Today);
                // Tạo đối tượng BookingInfomation từ dữ liệu được gửi từ view
                var bookingInfo = new BookingInfomation
                {

                    // Gán các thuộc tính của BookingInfomation từ viewModel
                    From = bookinginfo.From,
                    To = bookinginfo.To,
                    Commodity = bookinginfo.Commodity,
                    PriceOwner = bookinginfo.PriceOwner,
                    CutOffSi = today.AddDays(14),
                    CutOffCy = today.AddDays(12),
                     UserId = user.Id,
                };
                // Thêm thông tin đặt chỗ vào cơ sở dữ liệu thông qua repository
                await _bookinginfomationRepository.AddAsync(bookingInfo);
                // Chuyển hướng người dùng đến trang chi tiết của thông tin đặt chỗ sau khi thêm thành công
                return RedirectToAction("CreateBillOfLading", "BillOfLading");
            }
            catch (Exception ex)
            {



                return RedirectToAction("Error", "Home");
            }
        }
        public IActionResult tracking()
        {
            var tracking = _logisticsContext.BookingInfomations.ToList();
            return View(tracking);
        }
    }
}

LogisticsWebsite_WebProgramingProject/Controllers/ScheduleController.cs
using LogisticsWebsite_WebProgramingProject.Repositories;
using LogisticsWebsite_WebProgramingProject.Repositories.Admin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LogisticsWebsite_WebProgramingProject.Controllers
{
    public class ScheduleController : Controller
    {
       
        private readonly IScheduleRepository _IScheduleRepository;
        private readonly IPortRepository _IPortRepository;

        public ScheduleController( IScheduleRepository iScheduleRepository, IPortRepository portRepository)
        {
            _IScheduleRepository = iScheduleRepository;
            _IPortRepository = portRepository;
        }
        public async Task<IActionResult> Index()
        {
            var Sche = await _IScheduleRepository.GetAsync();
            return View(Sche);
        }
    }
}

LogisticsWebsite_WebProgramingProject/Views/Schedule/Index.cshtml
@using LogisticsWebsite_WebProgramingProject.Models;
@model IEnumerable<LogisticsWebsite_WebProgramingProject.Models.Schedule>
@{
	ViewData["Title"] = "Index";

	var _context = new LogisticsContext();

}
<link href="~/css/assets/css/app.min.css" rel="stylesheet" />
@* <link href="~/css/Schedule.css" rel="stylesheet" /> *@
<div class="row" style="padding-top: 200px;">
	<div class="search-container">
		<label for="search-pod">POD: </label>
		<input class="form-control me-2" type="text" id="search-pod" name="search-pod" placeholder="POD" aria-label="Search">
		@* <input type="text" id="search-pod" name="search-pod"> *@
		<label for="search-pol">POL: </label> 
		<input class="form-control me-2" type="text" id="search-pol" name="search-pol" placeholder="POL" aria-label="Search">
		@* <input type="text" id="search-pol" name="search-pol">   *@
		@* <button type="button" onclick="searchByPorts()">Search</button> *@
		<button class="btn btn-outline-success" type="button" onclick="searchByPorts()">Search</button>
	</div>
</div>
<div class="table">
	<div class="card-container row">
		@foreach (var sche in Model)
		{
			<div class="col-md-4 mb-4" >
				<div class="card" style="background-color: #cddcf7;">
					<div class="card-body">
						@{
							var podOrder = await _context.Ports.FindAsync(sche.Pod);
							var polOrder = await _context.Ports.FindAsync(sche.Pol);

							if (podOrder != null && polOrder != null)
							{
								var podOrderName = podOrder.Name;
								var polOrderName = polOrder.Name;
								<h5 class="card-title">Schedule: @podOrderName -> @polOrderName</h5>
							}
						}
						<div class="card-text">Ship Name: @sche.Ship.ShipName</div>
						<div class="card-text">Day Go: @sche.DayGo - @sche.DayCome</div>
						<div class="card-text">Time Go: @sche.TimeGo</div>
						@{
							float pri = (float)sche.Price;
							<div class="card-text">Price: $@pri</div>
						}
						<button class="btn btn-secondary" type="button" onclick="location.href='@Url.Action("Add", "BookingInfomation")'">Book</button>
					</div>
				</div>
			</div>
		}
	</div>
</div>

<script>
	function searchByPorts() {
		var podInput, polInput, filterPod, filterPol, cards, cardContainer, podOrderName, polOrderName, i, txtValue;

		podInput = document.getElementById('search-pod');
		polInput = document.getElementById('search-pol');
		filterPod = podInput.value.toLowerCase(); // Convert input to lowercase for case-insensitive search
		filterPol = polInput.value.toLowerCase(); // Convert input to lowercase for case-insensitive search

		cardContainer = document.getElementsByClassName('card-container')[0];
		cards = cardContainer.getElementsByClassName('card-body');

		for (i = 0; i < cards.length; i++) {
			podOrderName = cards[i].querySelector('.card-title').innerText.toLowerCase();
			polOrderName = cards[i].querySelector('.card-title').innerText.toLowerCase();

			// Check if either podOrderName or polOrderName includes either filter
			var isMatching = (podOrderName.includes(filterPod) || podOrderName.includes(filterPol)) &&
				(polOrderName.includes(filterPod) || polOrderName.includes(filterPol));

			if (isMatching) {
				cards[i].style.display = '';
			} else {
				cards[i].style.display = 'none';
			}
		}
	}
</script>