LogisticsWebsite_WebProgramingProject/Models/BillOfLading.cs
using System;
using System.Collections.Generic;

namespace LogisticsWebsite_WebProgramingProject.Models;

public partial class BillOfLading
{
    public int BillId { get; set; }

    public int BookingNo { get; set; }

    public int ScheduleId { get; set; }

    public int ContainerId { get; set; }

    public virtual BookingInfomation BookingNoNavigation { get; set; } = null!;

    public virtual ICollection<BookingWareHouse> BookingWareHouses { get; set; } = new List<BookingWareHouse>();

    public virtual Container Container { get; set; } = null!;

    public virtual ICollection<CostsIncurred> CostsIncurreds { get; set; } = new List<CostsIncurred>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual Schedule Schedule { get; set; } = null!;

    public virtual ICollection<Tracking> Trackings { get; set; } = new List<Tracking>();
}

LogisticsWebsite_WebProgramingProject/Controllers/BillOfLadingController.cs
using LogisticsWebsite_WebProgramingProject.Models;
using LogisticsWebsite_WebProgramingProject.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace LogisticsWebsite_WebProgramingProject.Controllers
{
    [Authorize]
    public class BillOfLadingController : Controller
    {
        private readonly LogisticsContext _context;
        private readonly IBillofladingRepository _billOfLading;
        private readonly IBookinginfomationRepository _bookinginfomation;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IContainerRepository _container;
        private readonly IScheduleRepository _scheduleReponsitory;
        private readonly ITrackingRepository _tracking;
        private readonly ILogger<BillOfLadingController> _logger;
        public BillOfLadingController(LogisticsContext context, IContainerRepository container, IScheduleRepository scheduleReponsitory,
            IBookinginfomationRepository bookinginfomation, UserManager<ApplicationUser> userManager, ITrackingRepository tracking, ILogger<BillOfLadingController> logger)
        {
            _context = context;
            _container = container;
            _scheduleReponsitory = scheduleReponsitory;
            _userManager = userManager;
            _bookinginfomation = bookinginfomation;
            _tracking = tracking;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CreateBillOfLading()
        {
            var bookingInfos = await _bookinginfomation.GetAllAsync();
            ViewBag.BookingNo = bookingInfos.LastOrDefault()?.BookingNo; 

          
            var containers = await _container.GetAllAsync();

            var containerSelectList = containers.Select(p => new SelectListItem
            {
                Value = p.ContainerId.ToString(),
                Text = $"Container - {p.ContainerSize} - {(p.Type ? "reefer " : "dry")}"
            }).ToList();
            var schedules = await _scheduleReponsitory.GetAllAsync();
            var scheduleOptions = schedules.Select(s => new
            {
                ScheduleId = s.ScheduleId,
                DisplayText = $"{s.DayGo.ToShortDateString()} - Price: {s.Price}$" // Kết hợp DayGo và Price
            }).ToList();

            ViewBag.Schedules = new SelectList(scheduleOptions, "ScheduleId", "DisplayText");
            ViewBag.ContainerSelectList = containerSelectList;
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBillOfLading(BillOfLading billOfLading)
        {
            try
            {
                _context.BillOfLadings.Add(billOfLading);
                await _context.SaveChangesAsync();

                // Tạo một đối tượng Tracking và thiết lập các thuộc tính của nó
                var tracking = new Tracking
                {
                    Status = "Comingsoon", // Thay "YourStatusHere" bằng trạng thái bạn muốn đặt
                    BillId = billOfLading.BillId // Sử dụng BillOfLadingId từ đối tượng billOfLading mới được tạo
                };

               
                _context.Trackings.AddAsync(tracking);
                await _context.SaveChangesAsync(); 

                return RedirectToAction("Success", new { billId = billOfLading.BillId });
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while processing your request. Please try again later.");

                Console.WriteLine($"Error in CreateBillOfLading: {ex.Message}");

                return View(billOfLading);
            }
        }

        public IActionResult Success(int billId)
        {

            return View(billId);
        }

        public IActionResult Details(int? id)
        {


            try
            {
                var billOfLading = _context.BillOfLadings
                    .Include(b => b.BookingNoNavigation)
                        .ThenInclude(b => b.BillOfLadings)
                    .Include(b => b.Container)
                    .Include(b => b.Schedule)
                        .ThenInclude(s => s.PolNavigation)
                    .Include(b => b.Schedule)
                        .ThenInclude(s => s.PodNavigation)
                    .Include(b => b.BookingWareHouses)
                        .ThenInclude(bw => bw.WhareHouse)
                    .Include(b => b.Trackings)

                    .FirstOrDefault(m => m.BillId == id);

                return View(billOfLading);
            }
            catch (Exception ex)
            {

                _logger.LogError(ex, "Lỗi xảy ra khi lấy chi tiết vận đơn");
                return RedirectToAction("Error", "Home");
            }
        }


    }
}

LogisticsWebsite_WebProgramingProject/Views/BillOfLading/CreateBillOfLading.cshtml
@model LogisticsWebsite_WebProgramingProject.Models.BillOfLading
<form asp-action="CreateBillOfLading" method="post">
    <div class="bodyy">
        <!-- Container image -->
        <section class="Image-Containerr">
        </section>
        <!-- Registration Form -->
        <div class="containerr">
            <div class="input-box">
                <label for="containerId">Container:</label>
                @Html.DropDownListFor(model => model.ContainerId, ViewBag.ContainerSelectList as List<SelectListItem>, "Select Container", new { @class = "form-control", @required = "required" })
            </div>
            <input type="hidden" name="BookingNo" value="@ViewBag.BookingNo" /> <!-- Ensure the name matches the parameter name in the action method -->
            <!-- Dropdownlist for Schedule -->
            <div class="input-box">
                <label for="scheduleId">Schedule:</label>
                @Html.DropDownListFor(model => model.ScheduleId, (SelectList)ViewBag.Schedules, "Select Schedule", new { @class = "form-control", @required = "required" })
            </div>
            <button class="submit_button" type="submit">Continue</button> <!-- Ensure you have a submit button -->
        </div>
    </div>
</form>

LogisticsWebsite_WebProgramingProject/Views/BillOfLading/Details.cshtml
@model LogisticsWebsite_WebProgramingProject.Models.BillOfLading




<div class="Bill_Of_Lading_Details" style=" padding-top: 100px">
    <h1>Bill of Lading Details</h1>

    <form method="post" asp-controller="BillOfLading" asp-action="Details">
        <div class="form-group">
            <label for="billId">Enter Bill ID:</label>
            <input type="text" class="form-control" id="billId" name="id">
        </div>
        <br />
        <button type="submit" class="btn btn-primary">View Details</button>
    </form>
    @if (Model != null)
    {

        <div>

            <dl class="row">
                <dt class="col-sm-2">
                    Booking Information
                </dt>
                <dd class="col-sm-10">
                    @Model.BookingNoNavigation.From - @Model.BookingNoNavigation.To

                </dd>
                <dt class="col-sm-2">
                    CustOffSi - CustOffCy
                </dt>
                <dd class="col-sm-10">
                    @Model.BookingNoNavigation.CutOffSi.ToString("dd/MM/yyyy") -
                    @Model.BookingNoNavigation.CutOffCy.ToString("dd/MM/yyyy")
                </dd>
                <dt class="col-sm-2">
                    Day Go - Day come
                </dt>
                <dd class="col-sm-10">
                    @Model.Schedule.DayGo.ToString("dd/MM/yyyy") -
                    @Model.Schedule.DayCome.ToString("dd/MM/yyyy")
                </dd>
                <dt class="col-sm-2">
                    Status
                </dt>
                <dd class="col-sm-10">
                    @{
                        var trackingForBill = Model.Trackings.FirstOrDefault(t => t.BillId == Model.BillId);
                        if (trackingForBill != null)
                        {
                            @trackingForBill.Status
                        }

                    }
                </dd>

                <dt class="col-sm-2">
                    Warehouses-Dayin
                </dt>
                <dd class="col-sm-10">
                    <ul>
                        @foreach (var bookingWarehouse in Model.BookingWareHouses)
                        {
                            <li> ID:@bookingWarehouse.WhareHouse.WhareHouseId  - Day in: @bookingWarehouse.Dayin </li>
                        }
                    </ul>
                </dd>

            </dl>
        </div>

        <div>
            <a asp-action="Index" asp-controller="Home">Back to Home</a>
        </div>
    }

</div>

LogisticsWebsite_WebProgramingProject/Views/BillOfLading/Success.cshtml
@model int
<body>
    <!-- Congratulations area start -->
    <div class="congratulation-area text-center mt-5" style="padding-top: 20px">
        <div class="container">
            <div class="congratulation-wrapper">
                <div class="congratulation-contents center-text">
                    <div class="congratulation-contents-icon">
                        <i class="fas fa-check"></i>
                    </div>
                    <h4 class="congratulation-contents-title"> Quote successful! </h4>
                    <p class="congratulation-contents-para"> Our system is analyzing your request and will provide your quote's Bill ID: " @Model "   within 20 minutes. </p>
                    <div class="btn-wrapper mt-4">
                        <a class="cmn-btn btn-bg-1" asp-controller="Home" asp-action="Index"> Go to Home </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Congratulations area end -->
    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>